/**
 * Official Data Seeding Functions
 *
 * Seeds official Bestiary monsters and features into Convex.
 * Run these via the Convex dashboard or CLI to populate data.
 *
 * Usage (from CLI):
 *   npx convex run seed:seedAllOfficialData
 *
 * Or individually:
 *   npx convex run seed:seedOfficialFeatures
 *   npx convex run seed:seedOfficialMonsters
 */

import { internalMutation, internalAction } from './_generated/server';
import { internal } from './_generated/api';

// ============================================================================
// OFFICIAL FEATURES DATA
// Directly embedded to avoid import issues with Convex
// ============================================================================

const OFFICIAL_FEATURES = [
	// 1-Point Features
	{
		id: 'feat_d4e5f678-1234-4abc-9def-012345678901',
		name: 'Keen Smell',
		description: 'ADV on Awareness Checks using smell.',
		pointCost: 1,
	},
	{
		id: 'feat_a1b2c3d4-5678-4ef0-1234-567890abcdef',
		name: 'Keen Sight',
		description: 'ADV on Awareness Checks using sight.',
		pointCost: 1,
	},
	{
		id: 'feat_b2c3d4e5-6789-4f01-2345-678901bcdefa',
		name: 'Large Lungs',
		description: 'Can hold breath for up to 1 hour.',
		pointCost: 1,
	},
	{
		id: 'feat_c3d4e5f6-789a-4012-3456-789012cdefab',
		name: 'False Appearance',
		description: 'Indistinguishable from regular object/terrain while motionless.',
		pointCost: 1,
	},
	{
		id: 'feat_d4e5f6a7-89ab-4123-4567-890123defabc',
		name: 'Hover',
		description: 'Hovers above the ground; immune to prone from non-magic.',
		pointCost: 1,
	},
	{
		id: 'feat_e5f6a7b8-9abc-4234-5678-901234efabcd',
		name: 'Bright Energy',
		description: 'Body provides Bright Light in 4-space radius.',
		pointCost: 1,
	},
	{
		id: 'feat_f6a7b8c9-abcd-4345-6789-012345fabcde',
		name: 'Forest Stride',
		description: 'Difficult terrain from plants does not slow movement.',
		pointCost: 1,
	},
	{
		id: 'feat_a7b8c9d0-bcde-4456-789a-123456abcdef',
		name: 'Amorphous',
		description: 'Can move through spaces as narrow as 1 inch.',
		pointCost: 1,
	},
	{
		id: 'feat_b8c9d0e1-cdef-4567-89ab-234567bcdefa',
		name: 'Keen Senses',
		description: 'ADV on Awareness Checks using hearing or smell.',
		pointCost: 1,
	},
	{
		id: 'feat_v3b1c2d3-1111-4111-1111-111111111111',
		name: 'Troop Tactics',
		description: 'Help Dice granted start as a d10.',
		pointCost: 1,
	},
	{
		id: 'feat_v3b2c3d4-2222-4222-2222-222222222222',
		name: 'Drawn to Sound',
		description:
			'Taunted by high-pitched sounds (music, screams, verbal components) within 10 spaces.',
		pointCost: 1,
	},
	{
		id: 'feat_v3b3c4d5-3333-4333-3333-333333333333',
		name: 'Sweet Scent',
		description: '5 Space Aura: Allies gain +1 to Attacks.',
		pointCost: 1,
	},
	// 2-Point Features
	{
		id: 'feat_c9d0e1f2-def0-4678-9abc-345678cdefab',
		name: 'Incorporeal Movement',
		description: 'Can move through creatures and objects (takes damage if ending turn in object).',
		pointCost: 2,
	},
	{
		id: 'feat_d0e1f2a3-ef01-4789-abcd-456789defabc',
		name: 'Wispy Form',
		description: 'Resistance to non-magical physical damage.',
		pointCost: 2,
	},
	{
		id: 'feat_e1f2a3b4-f012-489a-bcde-567890efabcd',
		name: 'Fiery Retribution',
		description: 'When hit by melee attack, attacker takes 1 Fire damage.',
		pointCost: 2,
	},
	{
		id: 'feat_f2a3b4c5-0123-49ab-cdef-678901fabcde',
		name: 'Forceful',
		description: 'Attacks push target 1 space on hit.',
		pointCost: 2,
	},
	{
		id: 'feat_a3b4c5d6-1234-4abc-def0-789012abcdef',
		name: 'Pack Tactics',
		description: 'ADV on attacks when ally is adjacent to target.',
		pointCost: 2,
	},
	{
		id: 'feat_b4c5d6e7-2345-4bcd-ef01-890123bcdefa',
		name: 'Telepathic Link',
		description: 'Telepathic link with master at any distance on the same plane.',
		pointCost: 2,
	},
	{
		id: 'feat_c5d6e7f8-3456-4cde-f012-901234cdefab',
		name: 'Tunneler',
		description: 'Burrow through solid stone leaving a 1-space tunnel.',
		pointCost: 2,
	},
	{
		id: 'feat_d6e7f8a9-4567-4def-0123-012345defabc',
		name: 'Spider Climb',
		description: 'Walk on ceilings and vertical surfaces normally.',
		pointCost: 2,
	},
	{
		id: 'feat_e7f8a9b0-5678-4ef0-1234-123456efabcd',
		name: 'Web Walk',
		description: 'Walk through webs unimpeded; know location of creatures on same web.',
		pointCost: 2,
	},
	{
		id: 'feat_v3c1d2e3-4444-4444-4444-444444444444',
		name: 'Reconstitution',
		description: 'Reaction: Self or Thrall within 15 spaces gains 2 Temp HP on damage.',
		pointCost: 2,
	},
	{
		id: 'feat_v3c2d3e4-5555-4555-5555-555555555555',
		name: 'Invisibility',
		description: 'Invisible while in Dim Light or Darkness.',
		pointCost: 2,
	},
	{
		id: 'feat_v3c3d4e5-6666-4666-6666-666666666666',
		name: 'Shadow Merge',
		description: 'Become Invisible when taking the Hide action in Dim Light.',
		pointCost: 2,
	},
	{
		id: 'feat_v3c4d5e6-7777-4777-7777-777777777777',
		name: 'Fiery Wake',
		description: 'Leaves a trail of flames that deal 1 Fire damage.',
		pointCost: 2,
	},
	{
		id: 'feat_v3c5d6e7-8888-4888-8888-888888888888',
		name: 'Elemental Siphon',
		description: 'Reaction: Split lightning damage with a nearby creature.',
		pointCost: 2,
	},
	{
		id: 'feat_v3c6d7e8-9999-4999-9999-999999999999',
		name: 'Plague Body',
		description: 'Creatures ending turn nearby contract Rot Plague.',
		pointCost: 2,
	},
	{
		id: 'feat_v3c7d8e9-aaaa-4aaa-aaaa-aaaaaaaaaaaa',
		name: 'Frost Aura',
		description: 'Regain 1 HP and slow nearby enemies at start of turn.',
		pointCost: 2,
	},
	{
		id: 'feat_v3c8d9e0-bbbb-4bbb-bbbb-bbbbbbbbbbbb',
		name: 'Telepathic Lure',
		description: '10 Space Aura: Humanoids must Save or be Taunted by familiar voices.',
		pointCost: 2,
	},
	{
		id: 'feat_v3c9d0e1-cccc-4ccc-cccc-cccccccccccc',
		name: 'Toxic Growth',
		description: 'Gain Toxic Mass stacks from Corrosion/Poison damage; +1 to Attacks per stack.',
		pointCost: 2,
	},
	{
		id: 'feat_v3d0e1f2-dddd-4ddd-dddd-dddddddddddd',
		name: 'Toxic Vines',
		description: 'Creatures with conditions from you take 1 Poison damage at start of turn.',
		pointCost: 2,
	},
	{
		id: 'feat_v3d1e2f3-eeee-4eee-eeee-eeeeeeeeeeee',
		name: 'Wrangling Vines',
		description: 'Can Grapple up to 4 different creatures at once.',
		pointCost: 2,
	},
	// 3-Point Features
	{
		id: 'feat_f8a9b0c1-6789-4f01-2345-234567fabcde',
		name: 'Spellcaster',
		description: '+2 bonus to Spell Duels.',
		pointCost: 3,
	},
	{
		id: 'feat_a9b0c1d2-789a-4012-3456-345678abcdef',
		name: 'Unrelenting',
		description: 'Only reduced below 1 HP by Heavy Hits or Radiant damage.',
		pointCost: 3,
	},
	{
		id: 'feat_b0c1d2e3-89ab-4123-4567-456789bcdefa',
		name: 'Stress',
		description: 'Loses DR and -5 Defenses at 3 Stress points.',
		pointCost: 3,
	},
	{
		id: 'feat_c1d2e3f4-9abc-4234-5678-567890cdefab',
		name: 'Dimensional Disruption',
		description: 'Radiant damage prevents Engulf until next turn.',
		pointCost: 3,
	},
	{
		id: 'feat_d2e3f4a5-abcd-4345-6789-678901defabc',
		name: 'Immutable Form',
		description: 'Immune to any spell or effect that would alter form.',
		pointCost: 3,
	},
	{
		id: 'feat_v3e1f2a3-ffff-4fff-ffff-ffffffffffff',
		name: 'Soul Collector',
		description: 'Collects souls of those who die within 5 spaces.',
		pointCost: 3,
	},
	{
		id: 'feat_v3e2f3a4-0000-4000-0000-000000000000',
		name: 'Water Body',
		description: 'Occupy same space as others. Creatures inside take 2 Corrosion and are Slowed.',
		pointCost: 3,
	},
];

// ============================================================================
// OFFICIAL MONSTERS DATA
// Pre-computed from sampleMonsters.ts to avoid bundling issues
// ============================================================================

const OFFICIAL_MONSTERS = [
	{
		id: 'mon_v2_chimera_001',
		name: 'Arctic Chimera',
		level: 4,
		tier: 'apex',
		roleId: 'brute',
		size: 'Large',
		monsterType: 'Beast',
		finalHP: 80,
		finalPD: 11,
		finalAD: 15,
		finalAttack: 6,
		finalSaveDC: 16,
		finalBaseDamage: 3,
		attributes: { might: 3, agility: 1, charisma: -1, intelligence: -2 },
		featureIds: ['feat_d4e5f678-1234-4abc-9def-012345678901', 'feat_b2c3d4e5-6789-4f01-2345-678901bcdefa'],
		featurePointsSpent: 2,
		featurePointsMax: 4,
		actions: [
			{
				id: 'act_chimera_maul',
				name: 'Maul',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 3,
				damageType: 'physical',
				description: 'Heavy Hit (+1)',
			},
			{
				id: 'act_chimera_crash',
				name: 'Crash',
				apCost: 1,
				type: 'special',
				targetDefense: 'ad',
				damage: 3,
				description: '2 Space Line',
			},
			{
				id: 'act_chimera_spray',
				name: 'Spray',
				apCost: 2,
				type: 'special',
				targetDefense: 'ad',
				damage: 2,
				description: '5 Space Line, Knockdown',
			},
		],
		schemaVersion: '1.0.0',
	},
	{
		id: 'mon_v2_necro_002',
		name: 'Necromancer',
		level: 4,
		tier: 'apex',
		roleId: 'leader',
		size: 'Medium',
		monsterType: 'Humanoid',
		finalHP: 40,
		finalPD: 13,
		finalAD: 15,
		finalAttack: 6,
		finalSaveDC: 16,
		finalBaseDamage: 2,
		attributes: { might: -1, agility: 1, charisma: 2, intelligence: 3 },
		featureIds: ['feat_f8a9b0c1-6789-4f01-2345-234567fabcde', 'feat_v3c1d2e3-4444-4444-4444-444444444444'],
		featurePointsSpent: 5,
		featurePointsMax: 4,
		actions: [
			{
				id: 'act_necro_bolt',
				name: 'Umbral Bolt',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 2,
				damageType: 'umbral',
				description: 'Sap Enhancement',
			},
			{
				id: 'act_necro_command',
				name: 'Command Thrall',
				apCost: 2,
				type: 'special',
				targetDefense: 'pd',
				damage: 0,
				description: 'One Thrall moves and attacks with ADV.',
			},
			{
				id: 'act_necro_create',
				name: 'Create Undead',
				apCost: 2,
				type: 'special',
				targetDefense: 'pd',
				damage: 0,
				description: 'Summon 1 Thrall within 5 spaces.',
			},
		],
		schemaVersion: '1.0.0',
	},
	{
		id: 'mon_v2_collector_003',
		name: 'Collector Demon',
		level: 5,
		tier: 'legendary',
		roleId: 'controller',
		size: 'Huge',
		monsterType: 'Fiend',
		finalHP: 70,
		finalPD: 14,
		finalAD: 17,
		finalAttack: 8,
		finalSaveDC: 18,
		finalBaseDamage: 3,
		attributes: { might: 2, agility: 0, charisma: 3, intelligence: 2 },
		featureIds: ['feat_v3e1f2a3-ffff-4fff-ffff-ffffffffffff', 'feat_v3c2d3e4-5555-4555-5555-555555555555'],
		featurePointsSpent: 5,
		featurePointsMax: 5,
		actions: [
			{
				id: 'act_collector_claws',
				name: 'Dark Claws',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 3,
				damageType: 'physical',
				description: '',
			},
			{
				id: 'act_collector_doom',
				name: 'Doom Call',
				apCost: 2,
				type: 'special',
				targetDefense: 'ad',
				damage: 1,
				description: '5 Space Aura, Doomed',
			},
		],
		schemaVersion: '1.0.0',
	},
	{
		id: 'mon_v2_penguin_004',
		name: 'Emperor Penguin',
		level: 3,
		tier: 'legendary',
		roleId: 'leader',
		size: 'Large',
		monsterType: 'Beast',
		finalHP: 60,
		finalPD: 14,
		finalAD: 17,
		finalAttack: 6,
		finalSaveDC: 16,
		finalBaseDamage: 2,
		attributes: { might: 1, agility: 2, charisma: 2, intelligence: 0 },
		featureIds: [],
		featurePointsSpent: 0,
		featurePointsMax: 3,
		actions: [
			{
				id: 'act_penguin_flipper',
				name: 'Flipper',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 2,
				damageType: 'physical',
				description: '',
			},
			{
				id: 'act_penguin_stare',
				name: 'Icy Stare',
				apCost: 2,
				type: 'special',
				targetDefense: 'ad',
				damage: 2,
				description: '10 Space Line, Immobilized',
			},
		],
		schemaVersion: '1.0.0',
	},
	{
		id: 'mon_v2_blightq_005',
		name: 'Blight Queen',
		level: 1,
		tier: 'apex',
		roleId: 'skirmisher',
		size: 'Large',
		monsterType: 'Monstrosity',
		finalHP: 25,
		finalPD: 15,
		finalAD: 9,
		finalAttack: 4,
		finalSaveDC: 14,
		finalBaseDamage: 2,
		attributes: { might: 2, agility: 3, charisma: -1, intelligence: 0 },
		featureIds: [],
		featurePointsSpent: 0,
		featurePointsMax: 1,
		actions: [
			{
				id: 'act_blight_pincer',
				name: 'Pincer',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 2,
				damageType: 'physical',
				description: 'Grapple',
			},
			{
				id: 'act_blight_spray',
				name: 'Corrosive Spray',
				apCost: 2,
				type: 'special',
				targetDefense: 'ad',
				damage: 1,
				description: '5 Space Cone, Burning',
			},
		],
		schemaVersion: '1.0.0',
	},
	{
		id: 'mon_v2_shadow_006',
		name: 'Shadow',
		level: 1,
		tier: 'standard',
		roleId: 'lurker',
		size: 'Medium',
		monsterType: 'Undead',
		finalHP: 7,
		finalPD: 13,
		finalAD: 10,
		finalAttack: 4,
		finalSaveDC: 14,
		finalBaseDamage: 1,
		attributes: { might: -1, agility: 3, charisma: 0, intelligence: 0 },
		featureIds: ['feat_v3c3d4e5-6666-4666-6666-666666666666'],
		featurePointsSpent: 2,
		featurePointsMax: 1,
		actions: [
			{
				id: 'act_shadow_rend',
				name: 'Soul Rend',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 1,
				damageType: 'umbral',
				description: 'Doomed',
			},
			{
				id: 'act_shadow_stride',
				name: 'Night Stride',
				apCost: 1,
				type: 'special',
				targetDefense: 'pd',
				damage: 0,
				description: 'Teleport 5 spaces between shadows.',
			},
		],
		schemaVersion: '1.0.0',
	},
	{
		id: 'mon_v2_cinder_007',
		name: 'Cindergeist',
		level: 3,
		tier: 'standard',
		roleId: 'lurker',
		size: 'Medium',
		monsterType: 'Undead',
		finalHP: 11,
		finalPD: 14,
		finalAD: 11,
		finalAttack: 5,
		finalSaveDC: 15,
		finalBaseDamage: 3,
		attributes: { might: 0, agility: 3, charisma: 1, intelligence: 0 },
		featureIds: [],
		featurePointsSpent: 0,
		featurePointsMax: 3,
		actions: [
			{
				id: 'act_cinder_lash',
				name: 'Ash Lash',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 3,
				damageType: 'fire',
				description: 'Fire/Umbral',
			},
			{
				id: 'act_cinder_drift',
				name: 'Ember Drift',
				apCost: 3,
				type: 'special',
				targetDefense: 'ad',
				damage: 0,
				description: 'Fly 5 spaces, applying Burning and Blinded.',
			},
		],
		schemaVersion: '1.0.0',
	},
	{
		id: 'mon_v2_serpent_008',
		name: 'Flamewrought Serpent',
		level: 2,
		tier: 'standard',
		roleId: 'skirmisher',
		size: 'Large',
		monsterType: 'Elemental',
		finalHP: 13,
		finalPD: 12,
		finalAD: 12,
		finalAttack: 4,
		finalSaveDC: 14,
		finalBaseDamage: 2,
		attributes: { might: 1, agility: 2, charisma: 0, intelligence: -1 },
		featureIds: ['feat_v3c4d5e6-7777-4777-7777-777777777777'],
		featurePointsSpent: 2,
		featurePointsMax: 2,
		actions: [
			{
				id: 'act_serpent_bite',
				name: 'Bite',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 2,
				damageType: 'fire',
				description: 'Fire',
			},
			{
				id: 'act_serpent_coil',
				name: 'Blazing Coil',
				apCost: 3,
				type: 'special',
				targetDefense: 'ad',
				damage: 1,
				description: '3 Space Aura, Burning',
			},
		],
		schemaVersion: '1.0.0',
	},
	{
		id: 'mon_v2_gargoyle_009',
		name: 'Gargoyle',
		level: 3,
		tier: 'standard',
		roleId: 'defender',
		size: 'Medium',
		monsterType: 'Construct',
		finalHP: 15,
		finalPD: 15,
		finalAD: 15,
		finalAttack: 5,
		finalSaveDC: 15,
		finalBaseDamage: 2,
		attributes: { might: 2, agility: 0, charisma: -1, intelligence: 0 },
		featureIds: [],
		featurePointsSpent: 0,
		featurePointsMax: 3,
		actions: [
			{
				id: 'act_gargoyle_strike',
				name: 'Strike',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 2,
				damageType: 'physical',
				description: '',
			},
			{
				id: 'act_gargoyle_ram',
				name: 'Ram',
				apCost: 2,
				type: 'special',
				targetDefense: 'ad',
				damage: 0,
				description: 'Move and Strike, pushing target 1 space.',
			},
		],
		schemaVersion: '1.0.0',
	},
	{
		id: 'mon_v2_lbug_010',
		name: 'Lightning Bug',
		level: 2,
		tier: 'standard',
		roleId: 'lurker',
		size: 'Tiny',
		monsterType: 'Elemental',
		finalHP: 10,
		finalPD: 15,
		finalAD: 8,
		finalAttack: 4,
		finalSaveDC: 14,
		finalBaseDamage: 2,
		attributes: { might: -2, agility: 3, charisma: 0, intelligence: 0 },
		featureIds: ['feat_v3c5d6e7-8888-4888-8888-888888888888'],
		featurePointsSpent: 2,
		featurePointsMax: 2,
		actions: [
			{
				id: 'act_lbug_bolt',
				name: 'Lightning Bolt',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 2,
				damageType: 'lightning',
				description: '',
			},
			{
				id: 'act_lbug_burst',
				name: 'Flicker Burst',
				apCost: 2,
				type: 'special',
				targetDefense: 'ad',
				damage: 1,
				description: '3 Space Aura, Teleport',
			},
		],
		schemaVersion: '1.0.0',
	},
	{
		id: 'mon_v2_phound_011',
		name: 'Plague Hound',
		level: 2,
		tier: 'standard',
		roleId: 'skirmisher',
		size: 'Medium',
		monsterType: 'Monstrosity',
		finalHP: 12,
		finalPD: 11,
		finalAD: 8,
		finalAttack: 4,
		finalSaveDC: 14,
		finalBaseDamage: 2,
		attributes: { might: 1, agility: 2, charisma: -1, intelligence: -2 },
		featureIds: ['feat_v3c6d7e8-9999-4999-9999-999999999999'],
		featurePointsSpent: 2,
		featurePointsMax: 2,
		actions: [
			{
				id: 'act_phound_rend',
				name: 'Rend',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 2,
				damageType: 'poison',
				description: 'Poisoned',
			},
			{
				id: 'act_phound_breath',
				name: 'Plague Breath',
				apCost: 3,
				type: 'special',
				targetDefense: 'ad',
				damage: 2,
				description: '3 Space Cone',
			},
		],
		schemaVersion: '1.0.0',
	},
	{
		id: 'mon_v2_sentinel_012',
		name: 'Rime-Sculpted Sentinel',
		level: 2,
		tier: 'standard',
		roleId: 'controller',
		size: 'Large',
		monsterType: 'Construct',
		finalHP: 11,
		finalPD: 13,
		finalAD: 11,
		finalAttack: 4,
		finalSaveDC: 14,
		finalBaseDamage: 2,
		attributes: { might: 2, agility: -1, charisma: 0, intelligence: 1 },
		featureIds: ['feat_v3c7d8e9-aaaa-4aaa-aaaa-aaaaaaaaaaaa'],
		featurePointsSpent: 2,
		featurePointsMax: 2,
		actions: [
			{
				id: 'act_sentinel_slam',
				name: 'Frost Slam',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 2,
				damageType: 'cold',
				description: '',
			},
			{
				id: 'act_sentinel_winds',
				name: 'Arctic Winds',
				apCost: 3,
				type: 'special',
				targetDefense: 'ad',
				damage: 1,
				description: 'Frost Aura Area',
			},
		],
		schemaVersion: '1.0.0',
	},
	{
		id: 'mon_v2_rug_013',
		name: 'Animated Rug',
		level: 1,
		tier: 'standard',
		roleId: 'controller',
		size: 'Medium',
		monsterType: 'Construct',
		finalHP: 10,
		finalPD: 11,
		finalAD: 13,
		finalAttack: 4,
		finalSaveDC: 14,
		finalBaseDamage: 1,
		attributes: { might: 1, agility: 1, charisma: -2, intelligence: -2 },
		featureIds: [],
		featurePointsSpent: 0,
		featurePointsMax: 1,
		actions: [
			{
				id: 'act_rug_wrap',
				name: 'Wrap',
				apCost: 1,
				type: 'special',
				targetDefense: 'ad',
				damage: 0,
				description: 'Grapple',
			},
			{
				id: 'act_rug_squeeze',
				name: 'Squeeze',
				apCost: 1,
				type: 'special',
				targetDefense: 'ad',
				damage: 1,
				description: 'ADV vs Grappled',
			},
		],
		schemaVersion: '1.0.0',
	},
	{
		id: 'mon_v2_wardrobe_014',
		name: 'Animated Wardrobe',
		level: 2,
		tier: 'standard',
		roleId: 'defender',
		size: 'Large',
		monsterType: 'Construct',
		finalHP: 15,
		finalPD: 14,
		finalAD: 14,
		finalAttack: 4,
		finalSaveDC: 14,
		finalBaseDamage: 2,
		attributes: { might: 2, agility: -1, charisma: -2, intelligence: -1 },
		featureIds: [],
		featurePointsSpent: 0,
		featurePointsMax: 2,
		actions: [
			{
				id: 'act_wardrobe_slam',
				name: 'Door Slam',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 2,
				damageType: 'physical',
				description: 'Dazed',
			},
			{
				id: 'act_wardrobe_grasping',
				name: 'Grasping Clothes',
				apCost: 1,
				type: 'special',
				targetDefense: 'pd',
				damage: 0,
				description: 'Contest, Grapple',
			},
		],
		schemaVersion: '1.0.0',
	},
	{
		id: 'mon_v2_twig_015',
		name: 'Twig Blight',
		level: 1,
		tier: 'standard',
		roleId: 'controller',
		size: 'Medium',
		monsterType: 'Plant',
		finalHP: 8,
		finalPD: 13,
		finalAD: 11,
		finalAttack: 4,
		finalSaveDC: 14,
		finalBaseDamage: 1,
		attributes: { might: 0, agility: 1, charisma: -2, intelligence: 0 },
		featureIds: [],
		featurePointsSpent: 0,
		featurePointsMax: 1,
		actions: [
			{
				id: 'act_twig_whip',
				name: 'Branch Whip',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 1,
				damageType: 'physical',
				description: 'Grapple',
			},
			{
				id: 'act_twig_vines',
				name: 'Entangling Vines',
				apCost: 2,
				type: 'special',
				targetDefense: 'pd',
				damage: 0,
				description: 'Creates difficult terrain in a 2-space sphere.',
			},
		],
		schemaVersion: '1.0.0',
	},
	{
		id: 'mon_v2_cwisp_016',
		name: 'Cleansed Wisp',
		level: 1,
		tier: 'standard',
		roleId: 'support',
		size: 'Tiny',
		monsterType: 'Fey',
		finalHP: 10,
		finalPD: 13,
		finalAD: 10,
		finalAttack: 4,
		finalSaveDC: 14,
		finalBaseDamage: 1,
		attributes: { might: -2, agility: 2, charisma: 1, intelligence: 1 },
		featureIds: [],
		featurePointsSpent: 0,
		featurePointsMax: 1,
		actions: [
			{
				id: 'act_cwisp_discharge',
				name: 'Discharge',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 1,
				damageType: 'radiant',
				description: 'Exposed',
			},
			{
				id: 'act_cwisp_heal',
				name: "Nature's Healing",
				apCost: 2,
				type: 'special',
				targetDefense: 'pd',
				damage: 0,
				description: 'Target regains 1-2 HP.',
			},
		],
		schemaVersion: '1.0.0',
	},
	{
		id: 'mon_v2_corwisp_017',
		name: 'Corrupted Wisp',
		level: 1,
		tier: 'standard',
		roleId: 'controller',
		size: 'Tiny',
		monsterType: 'Fey',
		finalHP: 10,
		finalPD: 13,
		finalAD: 10,
		finalAttack: 4,
		finalSaveDC: 14,
		finalBaseDamage: 1,
		attributes: { might: -2, agility: 2, charisma: 1, intelligence: 1 },
		featureIds: [],
		featurePointsSpent: 0,
		featurePointsMax: 1,
		actions: [
			{
				id: 'act_corwisp_discharge',
				name: 'Corrupted Discharge',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 1,
				damageType: 'umbral',
				description: 'Necrosis',
			},
			{
				id: 'act_corwisp_manip',
				name: 'Manipulation',
				apCost: 1,
				type: 'special',
				targetDefense: 'pd',
				damage: 0,
				description: 'Force target to move or attack.',
			},
		],
		schemaVersion: '1.0.0',
	},
	{
		id: 'mon_v2_zombie_018',
		name: 'Zombie',
		level: 0,
		tier: 'standard',
		roleId: 'brute',
		size: 'Medium',
		monsterType: 'Undead',
		finalHP: 10,
		finalPD: 9,
		finalAD: 13,
		finalAttack: 3,
		finalSaveDC: 13,
		finalBaseDamage: 1,
		attributes: { might: 2, agility: -1, charisma: -2, intelligence: -3 },
		featureIds: ['feat_a9b0c1d2-789a-4012-3456-345678abcdef'],
		featurePointsSpent: 3,
		featurePointsMax: 0,
		actions: [
			{
				id: 'act_zombie_bite',
				name: 'Bite or Slam',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 1,
				damageType: 'physical',
				description: 'Infect',
			},
			{
				id: 'act_zombie_slam',
				name: 'Slam (Grappled)',
				apCost: 1,
				type: 'special',
				targetDefense: 'ad',
				damage: 1,
				description: '',
			},
		],
		schemaVersion: '1.0.0',
	},
	{
		id: 'mon_v2_goblin_019',
		name: 'Goblin',
		level: 0,
		tier: 'standard',
		roleId: 'skirmisher',
		size: 'Small',
		monsterType: 'Humanoid',
		finalHP: 8,
		finalPD: 11,
		finalAD: 11,
		finalAttack: 3,
		finalSaveDC: 13,
		finalBaseDamage: 1,
		attributes: { might: -1, agility: 2, charisma: 0, intelligence: 0 },
		featureIds: [],
		featurePointsSpent: 0,
		featurePointsMax: 0,
		actions: [
			{
				id: 'act_goblin_knife',
				name: 'Knife',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 1,
				damageType: 'physical',
				description: '',
			},
			{
				id: 'act_goblin_bow',
				name: 'Shortbow',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 1,
				damageType: 'physical',
				description: '',
			},
		],
		schemaVersion: '1.0.0',
	},
	{
		id: 'mon_v2_kobold_020',
		name: 'Kobold',
		level: 0,
		tier: 'standard',
		roleId: 'lurker',
		size: 'Small',
		monsterType: 'Humanoid',
		finalHP: 6,
		finalPD: 12,
		finalAD: 9,
		finalAttack: 3,
		finalSaveDC: 13,
		finalBaseDamage: 1,
		attributes: { might: -2, agility: 3, charisma: 0, intelligence: 0 },
		featureIds: ['feat_v3b1c2d3-1111-4111-1111-111111111111'],
		featurePointsSpent: 1,
		featurePointsMax: 0,
		actions: [
			{
				id: 'act_kobold_spear',
				name: 'Spear',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 1,
				damageType: 'physical',
				description: 'Extend Attack',
			},
			{
				id: 'act_kobold_trap',
				name: 'Trap',
				apCost: 1,
				type: 'special',
				targetDefense: 'pd',
				damage: 0,
				description: 'Set a hidden trap within 5 spaces.',
			},
		],
		schemaVersion: '1.0.0',
	},
	{
		id: 'mon_v2_dummy_021',
		name: 'Training Dummy',
		level: -1,
		tier: 'standard',
		roleId: 'defender',
		size: 'Medium',
		monsterType: 'Construct',
		finalHP: 6,
		finalPD: 12,
		finalAD: 12,
		finalAttack: 2,
		finalSaveDC: 12,
		finalBaseDamage: 1,
		attributes: { might: 0, agility: 0, charisma: -3, intelligence: -3 },
		featureIds: [],
		featurePointsSpent: 0,
		featurePointsMax: 0,
		actions: [
			{
				id: 'act_dummy_slam',
				name: 'Slam',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 1,
				damageType: 'physical',
				description: 'Grab',
			},
			{
				id: 'act_dummy_whirl',
				name: 'Whirlwind',
				apCost: 2,
				type: 'special',
				targetDefense: 'ad',
				damage: 1,
				description: '1 Space Aura',
			},
		],
		schemaVersion: '1.0.0',
	},
	{
		id: 'mon_v2_rat_022',
		name: 'Giant Rat',
		level: -1,
		tier: 'standard',
		roleId: 'skirmisher',
		size: 'Small',
		monsterType: 'Beast',
		finalHP: 5,
		finalPD: 10,
		finalAD: 10,
		finalAttack: 2,
		finalSaveDC: 12,
		finalBaseDamage: 1,
		attributes: { might: -1, agility: 2, charisma: -2, intelligence: -3 },
		featureIds: [],
		featurePointsSpent: 0,
		featurePointsMax: 0,
		actions: [
			{
				id: 'act_rat_bite',
				name: 'Bite',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 1,
				damageType: 'physical',
				description: 'Impair',
			},
			{
				id: 'act_rat_dart',
				name: 'Dart Around',
				apCost: 1,
				type: 'special',
				targetDefense: 'pd',
				damage: 0,
				description: 'Take Disengage and Move actions.',
			},
		],
		schemaVersion: '1.0.0',
	},
	{
		id: 'mon_v2_hhound_023',
		name: 'Hunting Hound',
		level: -1,
		tier: 'standard',
		roleId: 'controller',
		size: 'Small',
		monsterType: 'Beast',
		finalHP: 5,
		finalPD: 11,
		finalAD: 9,
		finalAttack: 2,
		finalSaveDC: 12,
		finalBaseDamage: 1,
		attributes: { might: 0, agility: 1, charisma: 0, intelligence: -2 },
		featureIds: [],
		featurePointsSpent: 0,
		featurePointsMax: 0,
		actions: [
			{
				id: 'act_hhound_bite',
				name: 'Bite',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 1,
				damageType: 'physical',
				description: 'Pin',
			},
			{
				id: 'act_hhound_intim',
				name: 'Intimidate',
				apCost: 1,
				type: 'special',
				targetDefense: 'pd',
				damage: 0,
				description: 'Contest to Intimidate target.',
			},
		],
		schemaVersion: '1.0.0',
	},
	{
		id: 'mon_v2_thief_024',
		name: 'Thief',
		level: -1,
		tier: 'standard',
		roleId: 'lurker',
		size: 'Medium',
		monsterType: 'Humanoid',
		finalHP: 4,
		finalPD: 12,
		finalAD: 8,
		finalAttack: 2,
		finalSaveDC: 12,
		finalBaseDamage: 1,
		attributes: { might: -1, agility: 2, charisma: 1, intelligence: 0 },
		featureIds: [],
		featurePointsSpent: 0,
		featurePointsMax: 0,
		actions: [
			{
				id: 'act_thief_dart',
				name: 'Dart',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 0,
				damageType: 'physical',
				description: 'Hinder',
			},
			{
				id: 'act_thief_dagger',
				name: 'Dagger',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 1,
				damageType: 'physical',
				description: '',
			},
		],
		schemaVersion: '1.0.0',
	},
	{
		id: 'mon_v2_thug_025',
		name: 'Thug',
		level: 0,
		tier: 'standard',
		roleId: 'skirmisher',
		size: 'Medium',
		monsterType: 'Humanoid',
		finalHP: 8,
		finalPD: 11,
		finalAD: 11,
		finalAttack: 3,
		finalSaveDC: 13,
		finalBaseDamage: 1,
		attributes: { might: 1, agility: 1, charisma: 0, intelligence: -1 },
		featureIds: [],
		featurePointsSpent: 0,
		featurePointsMax: 0,
		actions: [
			{
				id: 'act_thug_fist',
				name: 'Fist',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 1,
				damageType: 'physical',
				description: 'Trip, Grapple',
			},
			{
				id: 'act_thug_slam',
				name: 'Slam (Grappled)',
				apCost: 1,
				type: 'special',
				targetDefense: 'ad',
				damage: 1,
				description: '',
			},
		],
		schemaVersion: '1.0.0',
	},
	{
		id: 'mon_v2_thrall_026',
		name: 'Thrall',
		level: 1,
		tier: 'standard',
		roleId: 'support',
		size: 'Medium',
		monsterType: 'Undead',
		finalHP: 5,
		finalPD: 10,
		finalAD: 14,
		finalAttack: 4,
		finalSaveDC: 14,
		finalBaseDamage: 1,
		attributes: { might: 0, agility: 0, charisma: -2, intelligence: 1 },
		featureIds: [],
		featurePointsSpent: 0,
		featurePointsMax: 1,
		actions: [
			{
				id: 'act_thrall_attack',
				name: 'Attack',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 1,
				damageType: 'physical',
				description: 'Physical or Umbral',
			},
		],
		schemaVersion: '1.0.0',
	},
	{
		id: 'mon_v2_penguin_basic_027',
		name: 'Penguin',
		level: 0,
		tier: 'standard',
		roleId: 'skirmisher',
		size: 'Small',
		monsterType: 'Beast',
		finalHP: 5,
		finalPD: 10,
		finalAD: 10,
		finalAttack: 3,
		finalSaveDC: 13,
		finalBaseDamage: 1,
		attributes: { might: 0, agility: 1, charisma: 1, intelligence: -1 },
		featureIds: [],
		featurePointsSpent: 0,
		featurePointsMax: 0,
		actions: [
			{
				id: 'act_penguin_beak',
				name: 'Beak',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 1,
				damageType: 'physical',
				description: '',
			},
			{
				id: 'act_penguin_slide',
				name: 'Slip and Slide',
				apCost: 2,
				type: 'special',
				targetDefense: 'pd',
				damage: 0,
				description: 'Move up to swim speed while prone.',
			},
		],
		schemaVersion: '1.0.0',
	},
	{
		id: 'mon_v2_mmaker_028',
		name: 'Mischief Maker',
		level: 4,
		tier: 'standard',
		roleId: 'controller',
		size: 'Tiny',
		monsterType: 'Fey',
		finalHP: 20,
		finalPD: 20,
		finalAD: 20,
		finalAttack: 5,
		finalSaveDC: 15,
		finalBaseDamage: 1,
		attributes: { might: -2, agility: 3, charisma: 3, intelligence: 2 },
		featureIds: ['feat_b0c1d2e3-89ab-4123-4567-456789bcdefa'],
		featurePointsSpent: 3,
		featurePointsMax: 4,
		actions: [
			{
				id: 'act_mmaker_joke',
				name: 'Mocking Joke',
				apCost: 1,
				type: 'special',
				targetDefense: 'pd',
				damage: 0,
				description: 'Target is Taunted for 1 minute.',
			},
			{
				id: 'act_mmaker_disp',
				name: 'Dispersion',
				apCost: 2,
				type: 'special',
				targetDefense: 'ad',
				damage: 1,
				description: '1 Space Aura, Teleport',
			},
		],
		schemaVersion: '1.0.0',
	},
	// Volume 3 Monsters
	{
		id: 'mon_v3_oculoth_029',
		name: 'Oculoth',
		level: 1,
		tier: 'standard',
		roleId: 'lurker',
		size: 'Small',
		monsterType: 'Fiend',
		finalHP: 6,
		finalPD: 14,
		finalAD: 9,
		finalAttack: 4,
		finalSaveDC: 14,
		finalBaseDamage: 2,
		attributes: { might: -1, agility: 3, charisma: 0, intelligence: 1 },
		featureIds: ['feat_a1b2c3d4-5678-4ef0-1234-567890abcdef', 'feat_b4c5d6e7-2345-4bcd-ef01-890123bcdefa'],
		featurePointsSpent: 3,
		featurePointsMax: 1,
		actions: [
			{
				id: 'act_oculoth_talons',
				name: 'Talons',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 2,
				damageType: 'physical',
				description: 'Blinded Enhancement',
			},
			{
				id: 'act_oculoth_beam',
				name: 'Eye Beam',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 1,
				damageType: 'fire',
				description: 'Fire, Heavy Hit (+1)',
			},
			{
				id: 'act_oculoth_ray',
				name: 'Elemental Ray',
				apCost: 2,
				type: 'special',
				targetDefense: 'ad',
				damage: 1,
				description: '10 Space Line, Fire',
			},
		],
		schemaVersion: '1.0.0',
	},
	{
		id: 'mon_v3_screecher_030',
		name: 'Screecher Drone',
		level: 2,
		tier: 'standard',
		roleId: 'controller',
		size: 'Small',
		monsterType: 'Beast',
		finalHP: 10,
		finalPD: 12,
		finalAD: 12,
		finalAttack: 4,
		finalSaveDC: 15,
		finalBaseDamage: 1,
		attributes: { might: 0, agility: 1, charisma: -1, intelligence: -2 },
		featureIds: ['feat_v3b2c3d4-2222-4222-2222-222222222222'],
		featurePointsSpent: 1,
		featurePointsMax: 2,
		actions: [
			{
				id: 'act_screecher_claw',
				name: 'Claw',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 1,
				damageType: 'physical',
				description: 'Bleed, Grab',
			},
			{
				id: 'act_screecher_bite',
				name: 'Bloodsucking Bite',
				apCost: 1,
				type: 'special',
				targetDefense: 'ad',
				damage: 1,
				description: 'Requires Grappled, Doomed 1',
			},
			{
				id: 'act_screecher_screech',
				name: 'Sonic Screech',
				apCost: 2,
				type: 'special',
				targetDefense: 'ad',
				damage: 1,
				description: '5 Space Cone, Dazed',
			},
		],
		schemaVersion: '1.0.0',
	},
	{
		id: 'mon_v3_mawworm_031',
		name: 'Mawworm',
		level: 3,
		tier: 'standard',
		roleId: 'brute',
		size: 'Small',
		monsterType: 'Aberration',
		finalHP: 17,
		finalPD: 11,
		finalAD: 13,
		finalAttack: 5,
		finalSaveDC: 15,
		finalBaseDamage: 2,
		attributes: { might: 2, agility: 0, charisma: -2, intelligence: 0 },
		featureIds: ['feat_c1d2e3f4-9abc-4234-5678-567890cdefab', 'feat_c5d6e7f8-3456-4cde-f012-901234cdefab'],
		featurePointsSpent: 5,
		featurePointsMax: 3,
		actions: [
			{
				id: 'act_mawworm_bite',
				name: 'Bite',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 2,
				damageType: 'physical',
				description: 'Grapple',
			},
			{
				id: 'act_mawworm_sweep',
				name: 'Sweep',
				apCost: 2,
				type: 'special',
				targetDefense: 'ad',
				damage: 1,
				description: '1 Space Arc, Prone',
			},
			{
				id: 'act_mawworm_engulf',
				name: 'Engulf',
				apCost: 2,
				type: 'special',
				targetDefense: 'pd',
				damage: 0,
				description: 'Target Grappled must make Might Save or be Swallowed into interdimensional space.',
			},
		],
		schemaVersion: '1.0.0',
	},
	{
		id: 'mon_v3_mreaper_032',
		name: 'Marrow Reaper Spider',
		level: 5,
		tier: 'standard',
		roleId: 'lurker',
		size: 'Medium',
		monsterType: 'Beast',
		finalHP: 15,
		finalPD: 15,
		finalAD: 14,
		finalAttack: 7,
		finalSaveDC: 18,
		finalBaseDamage: 3,
		attributes: { might: 1, agility: 3, charisma: -1, intelligence: 0 },
		featureIds: ['feat_d6e7f8a9-4567-4def-0123-012345defabc', 'feat_e7f8a9b0-5678-4ef0-1234-123456efabcd'],
		featurePointsSpent: 4,
		featurePointsMax: 5,
		actions: [
			{
				id: 'act_mreaper_bite',
				name: 'Bite',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 2,
				damageType: 'poison',
				description: 'Corrosion, Poisoned (Limb Effects)',
			},
			{
				id: 'act_mreaper_leg',
				name: 'Leg Spear',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 3,
				damageType: 'physical',
				description: '3 Space Range, Pull',
			},
			{
				id: 'act_mreaper_drain',
				name: 'Marrow Drain',
				apCost: 2,
				type: 'martial',
				targetDefense: 'pd',
				damage: 3,
				damageType: 'umbral',
				description: 'Requires Poisoned, Heal',
			},
		],
		schemaVersion: '1.0.0',
	},
	{
		id: 'mon_v3_psymanta_033',
		name: 'Psymanta',
		level: 3,
		tier: 'standard',
		roleId: 'skirmisher',
		size: 'Large',
		monsterType: 'Aberration',
		finalHP: 13,
		finalPD: 13,
		finalAD: 13,
		finalAttack: 5,
		finalSaveDC: 15,
		finalBaseDamage: 2,
		attributes: { might: 0, agility: 2, charisma: 1, intelligence: 2 },
		featureIds: ['feat_v3c8d9e0-bbbb-4bbb-bbbb-bbbbbbbbbbbb'],
		featurePointsSpent: 2,
		featurePointsMax: 3,
		actions: [
			{
				id: 'act_psymanta_tendril',
				name: 'Mind Leech Tendril',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 2,
				damageType: 'psychic',
				description: 'Psychic, Dazed',
			},
			{
				id: 'act_psymanta_pulse',
				name: 'Psychic Pulse',
				apCost: 2,
				type: 'special',
				targetDefense: 'ad',
				damage: 1,
				description: '2 Space Aura, Force Movement',
			},
		],
		schemaVersion: '1.0.0',
	},
	{
		id: 'mon_v3_aooze_034',
		name: 'Aqua Ooze',
		level: 4,
		tier: 'standard',
		roleId: 'defender',
		size: 'Large',
		monsterType: 'Ooze',
		finalHP: 15,
		finalPD: 15,
		finalAD: 15,
		finalAttack: 5,
		finalSaveDC: 15,
		finalBaseDamage: 1,
		attributes: { might: 2, agility: -1, charisma: -3, intelligence: -3 },
		featureIds: ['feat_v3e2f3a4-0000-4000-0000-000000000000', 'feat_c3d4e5f6-789a-4012-3456-789012cdefab'],
		featurePointsSpent: 4,
		featurePointsMax: 4,
		actions: [
			{
				id: 'act_aooze_lash',
				name: 'Pressure Lash',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 1,
				damageType: 'physical',
				description: '3 Space Range, Pull',
			},
			{
				id: 'act_aooze_drown',
				name: 'Drown',
				apCost: 1,
				type: 'special',
				targetDefense: 'ad',
				damage: 1,
				description: 'Targets in Space, Suffocating',
			},
		],
		schemaVersion: '1.0.0',
	},
	{
		id: 'mon_v3_tslime_035',
		name: 'Toxic Slime',
		level: 5,
		tier: 'standard',
		roleId: 'brute',
		size: 'Large',
		monsterType: 'Ooze',
		finalHP: 28,
		finalPD: 12,
		finalAD: 16,
		finalAttack: 7,
		finalSaveDC: 17,
		finalBaseDamage: 4,
		attributes: { might: 3, agility: -1, charisma: -3, intelligence: -2 },
		featureIds: ['feat_v3c9d0e1-cccc-4ccc-cccc-cccccccccccc'],
		featurePointsSpent: 2,
		featurePointsMax: 5,
		actions: [
			{
				id: 'act_tslime_limb',
				name: 'Toxic Limb',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 4,
				damageType: 'corrosion',
				description: 'Corrosion',
			},
			{
				id: 'act_tslime_spit',
				name: 'Spit Slime',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 2,
				damageType: 'corrosion',
				description: 'Summon Mini Slime',
			},
			{
				id: 'act_tslime_decay',
				name: 'Decay',
				apCost: 2,
				type: 'special',
				targetDefense: 'ad',
				damage: 2,
				description: '2 Space Aura, Poisoned',
			},
		],
		schemaVersion: '1.0.0',
	},
	{
		id: 'mon_v3_cooze_036',
		name: 'Crimson Ooze',
		level: 4,
		tier: 'standard',
		roleId: 'skirmisher',
		size: 'Medium',
		monsterType: 'Ooze',
		finalHP: 15,
		finalPD: 10,
		finalAD: 15,
		finalAttack: 7,
		finalSaveDC: 17,
		finalBaseDamage: 3,
		attributes: { might: 1, agility: 0, charisma: -3, intelligence: -2 },
		featureIds: [],
		featurePointsSpent: 0,
		featurePointsMax: 4,
		actions: [
			{
				id: 'act_cooze_leech',
				name: 'Blood Leech',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 3,
				damageType: 'umbral',
				description: 'Umbral, Heal if target Bleeding',
			},
			{
				id: 'act_cooze_split',
				name: 'Sanguine Split',
				apCost: 1,
				type: 'special',
				targetDefense: 'pd',
				damage: 0,
				description: 'Spend 7 HP to create an exact copy of self with 7 HP.',
			},
			{
				id: 'act_cooze_pulse',
				name: 'Blood Pulse',
				apCost: 2,
				type: 'special',
				targetDefense: 'ad',
				damage: 1,
				description: '2 Space Aura, Bleeding',
			},
		],
		schemaVersion: '1.0.0',
	},
	{
		id: 'mon_v3_pshambler_037',
		name: 'Plant Shambler',
		level: 5,
		tier: 'standard',
		roleId: 'controller',
		size: 'Large',
		monsterType: 'Plant',
		finalHP: 20,
		finalPD: 17,
		finalAD: 14,
		finalAttack: 7,
		finalSaveDC: 17,
		finalBaseDamage: 3,
		attributes: { might: 2, agility: -1, charisma: 0, intelligence: 1 },
		featureIds: ['feat_v3d0e1f2-dddd-4ddd-dddd-dddddddddddd'],
		featurePointsSpent: 2,
		featurePointsMax: 5,
		actions: [
			{
				id: 'act_pshambler_slam',
				name: 'Slam',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 3,
				damageType: 'physical',
				description: 'Knockback',
			},
			{
				id: 'act_pshambler_vine',
				name: 'Vine',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 2,
				damageType: 'physical',
				description: '10 Space Range, Tethered',
			},
			{
				id: 'act_pshambler_terrain',
				name: 'Entangling Terrain',
				apCost: 2,
				type: 'special',
				targetDefense: 'pd',
				damage: 0,
				description: '5 Space Sphere: Targets make Save or are Restrained.',
			},
		],
		schemaVersion: '1.0.0',
	},
	{
		id: 'mon_v3_cbloom_038',
		name: 'Carnivorous Bloom',
		level: 2,
		tier: 'standard',
		roleId: 'support',
		size: 'Medium',
		monsterType: 'Plant',
		finalHP: 10,
		finalPD: 14,
		finalAD: 14,
		finalAttack: 4,
		finalSaveDC: 14,
		finalBaseDamage: 1,
		attributes: { might: 1, agility: 0, charisma: 0, intelligence: -2 },
		featureIds: ['feat_v3b3c4d5-3333-4333-3333-333333333333', 'feat_v3d1e2f3-eeee-4eee-eeee-eeeeeeeeeeee'],
		featurePointsSpent: 3,
		featurePointsMax: 2,
		actions: [
			{
				id: 'act_cbloom_bite',
				name: 'Bite',
				apCost: 1,
				type: 'martial',
				targetDefense: 'pd',
				damage: 1,
				damageType: 'physical',
				description: 'Grapple',
			},
			{
				id: 'act_cbloom_swallow',
				name: 'Swallow',
				apCost: 1,
				type: 'special',
				targetDefense: 'pd',
				damage: 0,
				description: 'Grappled target makes Save or is Swallowed; takes Corrosion damage.',
			},
			{
				id: 'act_cbloom_sap',
				name: 'Empowering Sap',
				apCost: 1,
				type: 'special',
				targetDefense: 'pd',
				damage: 0,
				description: 'Ally gains 2 Temp HP and ADV on next attack.',
			},
		],
		schemaVersion: '1.0.0',
	},
	{
		id: 'mon_v3_sporebloom_039',
		name: 'Sporebloom Trap',
		level: 1,
		tier: 'standard',
		roleId: 'lurker',
		size: 'Tiny',
		monsterType: 'Plant',
		finalHP: 9,
		finalPD: 10,
		finalAD: 10,
		finalAttack: 5,
		finalSaveDC: 15,
		finalBaseDamage: 2,
		attributes: { might: -2, agility: 0, charisma: -3, intelligence: -3 },
		featureIds: [],
		featurePointsSpent: 0,
		featurePointsMax: 1,
		actions: [
			{
				id: 'act_sporebloom_puff',
				name: 'Spore Puff',
				apCost: 1,
				type: 'special',
				targetDefense: 'ad',
				damage: 2,
				description: '2 Space Aura, Poison, Stunned',
			},
			{
				id: 'act_sporebloom_cloud',
				name: 'Spore Cloud',
				apCost: 2,
				type: 'special',
				targetDefense: 'pd',
				damage: 0,
				description: 'Create 5 Space Aura of spores; area is Heavily Obscured.',
			},
		],
		schemaVersion: '1.0.0',
	},
];

// ============================================================================
// INTERNAL MUTATIONS (called by actions)
// ============================================================================

export const _seedFeatures = internalMutation({
	args: {},
	handler: async (ctx) => {
		const now = new Date().toISOString();
		let created = 0;
		let updated = 0;

		for (const feature of OFFICIAL_FEATURES) {
			const existing = await ctx.db
				.query('features')
				.filter((q) =>
					q.and(q.eq(q.field('id'), feature.id), q.eq(q.field('isOfficial'), true))
				)
				.first();

			if (existing) {
				await ctx.db.patch(existing._id, {
					...feature,
					isOfficial: true,
					lastModified: now,
				});
				updated++;
			} else {
				await ctx.db.insert('features', {
					...feature,
					isOfficial: true,
					userId: undefined,
					visibility: 'private',
					approvalStatus: 'approved',
					isHomebrew: false,
					createdAt: now,
					lastModified: now,
					schemaVersion: '1.0.0',
				});
				created++;
			}
		}

		return { created, updated, total: OFFICIAL_FEATURES.length };
	},
});

export const _seedMonsters = internalMutation({
	args: {},
	handler: async (ctx) => {
		const now = new Date().toISOString();
		let created = 0;
		let updated = 0;

		for (const monster of OFFICIAL_MONSTERS) {
			const existing = await ctx.db
				.query('monsters')
				.filter((q) =>
					q.and(q.eq(q.field('id'), monster.id), q.eq(q.field('isOfficial'), true))
				)
				.first();

			if (existing) {
				await ctx.db.patch(existing._id, {
					...monster,
					isOfficial: true,
					lastModified: now,
				});
				updated++;
			} else {
				await ctx.db.insert('monsters', {
					...monster,
					isOfficial: true,
					userId: undefined,
					visibility: 'private',
					approvalStatus: 'approved',
					isHomebrew: false,
					createdAt: now,
					lastModified: now,
				});
				created++;
			}
		}

		return { created, updated, total: OFFICIAL_MONSTERS.length };
	},
});

// ============================================================================
// PUBLIC ACTIONS (callable via CLI or dashboard)
// ============================================================================

/**
 * Seed official features into the database
 * Usage: npx convex run seed:seedOfficialFeatures
 */
export const seedOfficialFeatures = internalAction({
	args: {},
	handler: async (ctx) => {
		const result = await ctx.runMutation(internal.seed._seedFeatures);
		console.log(`✅ Features seeded: ${result.created} created, ${result.updated} updated`);
		return result;
	},
});

/**
 * Seed official monsters into the database
 * Usage: npx convex run seed:seedOfficialMonsters
 */
export const seedOfficialMonsters = internalAction({
	args: {},
	handler: async (ctx) => {
		const result = await ctx.runMutation(internal.seed._seedMonsters);
		console.log(`✅ Monsters seeded: ${result.created} created, ${result.updated} updated`);
		return result;
	},
});

/**
 * Seed all official data (features + monsters)
 * Usage: npx convex run seed:seedAllOfficialData
 */
export const seedAllOfficialData = internalAction({
	args: {},
	handler: async (ctx) => {
		console.log('🌱 Seeding official data...');

		const featuresResult = await ctx.runMutation(internal.seed._seedFeatures);
		console.log(`  Features: ${featuresResult.created} created, ${featuresResult.updated} updated`);

		const monstersResult = await ctx.runMutation(internal.seed._seedMonsters);
		console.log(`  Monsters: ${monstersResult.created} created, ${monstersResult.updated} updated`);

		console.log('✅ All official data seeded successfully!');

		return {
			features: featuresResult,
			monsters: monstersResult,
		};
	},
});
