// This file was automatically generated by a script.
// **Manually review and update the 'classFeatures' array with correct feature IDs.**
// import { ClassLevel } from '../../schemas/class.schema'; // Adjust path as needed

// Awaiting schema update, using 'any' for now.
export const psionProgression: any[] = [
  {
    "level": 1,
    "gainedHealth": 8,
    "gainedAttributePoints": 0,
    "gainedSkillPoints": 0,
    "gainedTradePoints": 0,
    "gainedStaminaPoints": 1,
    "gainedManeuversKnown": 0,
    "gainedTechniquesKnown": 0,
    "gains": {
      "classFeatures": [
        "psion_spellcasting_path",
        "psion_stamina",
        "psion_psionic_mind",
        "psion_telekinesis",
        "psion_telekinetic_grapple",
        "psion_telepathy"
      ]
    }
  },
  {
    "level": 2,
    "gainedHealth": 2,
    "gainedAttributePoints": 0,
    "gainedSkillPoints": 0,
    "gainedTradePoints": 0,
    "gainedStaminaPoints": 0,
    "gainedManeuversKnown": 0,
    "gainedTechniquesKnown": 0,
    "gains": {
      "talents": 1,
      "pathPoints": 1,
      "classFeatures": [
        "psion_mind_sense",
        "psion_invade_mind",
        "psion_psionic_resolve",
        "psion_talent_level_2"
      ]
    }
  },
  {
    "level": 3,
    "gainedHealth": 2,
    "gainedAttributePoints": 1,
    "gainedSkillPoints": 1,
    "gainedTradePoints": 1,
    "gainedStaminaPoints": 0,
    "gainedManeuversKnown": 0,
    "gainedTechniquesKnown": 0,
    "gains": {
      "subclassFeatureChoice": true
    }
  },
  {
    "level": 4,
    "gainedHealth": 2,
    "gainedAttributePoints": 0,
    "gainedSkillPoints": 0,
    "gainedTradePoints": 0,
    "gainedStaminaPoints": 0,
    "gainedManeuversKnown": 0,
    "gainedTechniquesKnown": 0,
    "gains": {
      "talents": 1,
      "pathPoints": 1,
      "ancestryPoints": 2
    }
  },
  {
    "level": 5,
    "gainedHealth": 2,
    "gainedAttributePoints": 1,
    "gainedSkillPoints": 2,
    "gainedTradePoints": 1,
    "gainedStaminaPoints": 0,
    "gainedManeuversKnown": 0,
    "gainedTechniquesKnown": 0,
    "gains": {
      "classFeatures": [
        "placeholder_class_feature"
      ]
    }
  },
  {
    "level": 6,
    "gainedHealth": 2,
    "gainedAttributePoints": 1,
    "gainedSkillPoints": 1,
    "gainedTradePoints": 0,
    "gainedStaminaPoints": 1,
    "gainedManeuversKnown": 0,
    "gainedTechniquesKnown": 0,
    "gains": {
      "subclassFeatureChoice": true
    }
  },
  {
    "level": 7,
    "gainedHealth": 2,
    "gainedAttributePoints": 0,
    "gainedSkillPoints": 0,
    "gainedTradePoints": 0,
    "gainedStaminaPoints": 0,
    "gainedManeuversKnown": 0,
    "gainedTechniquesKnown": 0,
    "gains": {
      "talents": 1,
      "pathPoints": 1,
      "ancestryPoints": 2
    }
  },
  {
    "level": 8,
    "gainedHealth": 2,
    "gainedAttributePoints": 1,
    "gainedSkillPoints": 1,
    "gainedTradePoints": 1,
    "gainedStaminaPoints": 0,
    "gainedManeuversKnown": 0,
    "gainedTechniquesKnown": 0,
    "gains": {
      "classFeatures": [
        "placeholder_class_capstone"
      ]
    }
  },
  {
    "level": 9,
    "gainedHealth": 2,
    "gainedAttributePoints": 0,
    "gainedSkillPoints": 0,
    "gainedTradePoints": 0,
    "gainedStaminaPoints": 0,
    "gainedManeuversKnown": 0,
    "gainedTechniquesKnown": 0,
    "gains": {
      "subclassFeatureChoice": true
    }
  },
  {
    "level": 10,
    "gainedHealth": 2,
    "gainedAttributePoints": 1,
    "gainedSkillPoints": 2,
    "gainedTradePoints": 1,
    "gainedStaminaPoints": 0,
    "gainedManeuversKnown": 0,
    "gainedTechniquesKnown": 0,
    "gains": {
      "talents": 1,
      "pathPoints": 1,
      "epicBoon": true
    }
  }
];