// This file was automatically generated by a script.
// **Manually review and update the 'classFeatures' array with correct feature IDs.**
// import { ClassLevel } from '../../schemas/class.schema'; // Adjust path as needed

// Awaiting schema update, using 'any' for now.
export const wizardProgression: any[] = [
  {
    "level": 1,
    "gainedHealth": 8,
    "gainedAttributePoints": 0,
    "gainedSkillPoints": 0,
    "gainedTradePoints": 0,
    "gainedStaminaPoints": 0,
    "gainedManeuversKnown": 0,
    "gainedTechniquesKnown": 0,
    "gains": {
      "classFeatures": [
        "wizard_spellcasting_path",
        "wizard_spell_school_initiate",
        "wizard_arcane_sigil",
        "wizard_ritual_caster"
      ]
    }
  },
  {
    "level": 2,
    "gainedHealth": 2,
    "gainedAttributePoints": 0,
    "gainedSkillPoints": 0,
    "gainedTradePoints": 0,
    "gainedStaminaPoints": 0,
    "gainedManeuversKnown": 0,
    "gainedTechniquesKnown": 0,
    "gains": {
      "talents": 1,
      "pathPoints": 1,
      "classFeatures": [
        "wizard_prepared_spell",
        "wizard_talent_level_2"
      ]
    }
  },
  {
    "level": 3,
    "gainedHealth": 2,
    "gainedAttributePoints": 1,
    "gainedSkillPoints": 1,
    "gainedTradePoints": 1,
    "gainedStaminaPoints": 0,
    "gainedManeuversKnown": 0,
    "gainedTechniquesKnown": 0,
    "gains": {
      "subclassFeatureChoice": true
    }
  },
  {
    "level": 4,
    "gainedHealth": 2,
    "gainedAttributePoints": 0,
    "gainedSkillPoints": 0,
    "gainedTradePoints": 0,
    "gainedStaminaPoints": 0,
    "gainedManeuversKnown": 0,
    "gainedTechniquesKnown": 0,
    "gains": {
      "talents": 1,
      "pathPoints": 1,
      "ancestryPoints": 2
    }
  },
  {
    "level": 5,
    "gainedHealth": 2,
    "gainedAttributePoints": 1,
    "gainedSkillPoints": 2,
    "gainedTradePoints": 1,
    "gainedStaminaPoints": 0,
    "gainedManeuversKnown": 0,
    "gainedTechniquesKnown": 0,
    "gains": {
      "classFeatures": [
        "placeholder_class_feature"
      ]
    }
  },
  {
    "level": 6,
    "gainedHealth": 2,
    "gainedAttributePoints": 0,
    "gainedSkillPoints": 1,
    "gainedTradePoints": 0,
    "gainedStaminaPoints": 0,
    "gainedManeuversKnown": 0,
    "gainedTechniquesKnown": 0,
    "gains": {
      "subclassFeatureChoice": true
    }
  },
  {
    "level": 7,
    "gainedHealth": 2,
    "gainedAttributePoints": 0,
    "gainedSkillPoints": 0,
    "gainedTradePoints": 0,
    "gainedStaminaPoints": 0,
    "gainedManeuversKnown": 0,
    "gainedTechniquesKnown": 0,
    "gains": {
      "talents": 1,
      "pathPoints": 1,
      "ancestryPoints": 2
    }
  },
  {
    "level": 8,
    "gainedHealth": 2,
    "gainedAttributePoints": 1,
    "gainedSkillPoints": 1,
    "gainedTradePoints": 1,
    "gainedStaminaPoints": 0,
    "gainedManeuversKnown": 0,
    "gainedTechniquesKnown": 0,
    "gains": {
      "classFeatures": [
        "placeholder_class_capstone"
      ]
    }
  },
  {
    "level": 9,
    "gainedHealth": 2,
    "gainedAttributePoints": 0,
    "gainedSkillPoints": 0,
    "gainedTradePoints": 0,
    "gainedStaminaPoints": 0,
    "gainedManeuversKnown": 0,
    "gainedTechniquesKnown": 0,
    "gains": {
      "subclassFeatureChoice": true
    }
  },
  {
    "level": 10,
    "gainedHealth": 2,
    "gainedAttributePoints": 1,
    "gainedSkillPoints": 2,
    "gainedTradePoints": 1,
    "gainedStaminaPoints": 0,
    "gainedManeuversKnown": 0,
    "gainedTechniquesKnown": 0,
    "gains": {
      "talents": 1,
      "pathPoints": 1,
      "epicBoon": true
    }
  }
];