import { describe, it, expect } from 'vitest';
import { calculateCharacterWithBreakdowns } from './enhancedCharacterCalculator';
import { skillsData } from '../rulesdata/skills';
import { tradesData } from '../rulesdata/trades';

// Helper to create a minimal character build data
const createBaseBuild = (overrides = {}) => ({
    id: 'test-id',
    characterId: 'test-char-id',
    level: 1,
    attribute_might: 0,
    attribute_agility: 0,
    attribute_intelligence: 0,
    attribute_charisma: 0,
    skillsData: {},
    tradesData: {},
    languagesData: {},
    selectedTraitIds: [],
    classId: null,
    selectedFeatureChoices: {},
    selectedSpells: {},
    selectedManeuvers: [],
    ...overrides
});

describe('Spell System - Global Magic Profile', () => {
    it('should initialize empty profile for non-spellcasters', () => {
        const build = createBaseBuild({ classId: 'barbarian' });
        const result = calculateCharacterWithBreakdowns(build as any, skillsData, tradesData);

        expect(result.globalMagicProfile).toBeDefined();
        expect(result.globalMagicProfile?.allowedSources).toContain('Natural');
        expect(result.globalMagicProfile?.allowedSources).not.toContain('Arcane');
    });

    it('should include class sources for spellcasters', () => {
        const build = createBaseBuild({ classId: 'wizard' });
        const result = calculateCharacterWithBreakdowns(build as any, skillsData, tradesData);

        expect(result.globalMagicProfile?.allowedSources).toContain('Arcane');
    });

    it('should expand schools via features (e.g., Wizard Expanded School)', () => {
        const build = createBaseBuild({
            classId: 'wizard',
            selectedFeatureChoices: {
                'wizard_expanded_school_choice': 'Invocation'
            }
        });
        const result = calculateCharacterWithBreakdowns(build as any, skillsData, tradesData);

        expect(result.globalMagicProfile?.allowedSchools).toContain('Invocation');
    });
});

describe('Spell System - Spells Known Slots', () => {
    it('should generate base slots for spellcasters at level 1', () => {
        const build = createBaseBuild({ classId: 'wizard', level: 1 });
        const result = calculateCharacterWithBreakdowns(build as any, skillsData, tradesData);

        // Wizard at lvl 1 gets 3 cantrips and 2 spells (standard)
        const cantrips = result.spellsKnownSlots.filter(s => s.type === 'cantrip');
        const spells = result.spellsKnownSlots.filter(s => s.type === 'spell');

        expect(cantrips.length).toBe(3);
        expect(spells.length).toBe(2);
    });

    it('should handle specialized slots (e.g., Sorcerer extra spell)', () => {
        // Mock sorcerer subclass/feature if needed, but let's test a generic GRANT_SPELL effect
        const build = createBaseBuild({
            classId: 'sorcerer',
            level: 1
        });
        const result = calculateCharacterWithBreakdowns(build as any, skillsData, tradesData);

        // Sorcerer gets 1 extra spell from subclass choice at lvl 1 in our config
        // Total should be 2 (base) + 1 (special) = 3
        const spells = result.spellsKnownSlots.filter(s => s.type === 'spell');
        expect(spells.length).toBe(3);
    });
});

describe('Spell System - Validations', () => {
    it('should error when assigning a non-cantrip to a cantrip slot', () => {
        const build = createBaseBuild({
            classId: 'wizard',
            selectedSpells: {
                'wizard_cantrip_1': 'firebolt', // Assume firebolt is a cantrip
                'wizard_cantrip_2': 'fireball'  // Assume fireball is a spell
            }
        });

        // We need real spell IDs from rulesdata
        // Actually let's use known IDs: firebolt -> 'firebolt', fireball -> 'fireball'

        const result = calculateCharacterWithBreakdowns(build as any, skillsData, tradesData);
        const error = result.validation.errors.find(e => e.code === 'TYPE_MISMATCH');
        expect(error).toBeDefined();
        expect(error?.message).toContain('requires a cantrip');
    });

    it('should error when school restriction is violated', () => {
        // Slot that requires 'Elemental' schools
        const build = createBaseBuild({
            classId: 'wizard',
            selectedFeatureChoices: {
                'wizard_expanded_school_choice': 'Elemental'
            },
            selectedSpells: {
                // wizard_expanded_school_slot is generated by the feature
                'wizard_expanded_school_slot_Elemental': 'mind_sliver' // Enchantment
            }
        });

        const result = calculateCharacterWithBreakdowns(build as any, skillsData, tradesData);
        const error = result.validation.errors.find(e => e.code === 'SCHOOL_RESTRICTION');
        expect(error).toBeDefined();
    });
});
